/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Main } from "./index";

export const groupsSchemaJson = {
    "$ref": "#/definitions/Groups",
    "definitions": {
        "Groups": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Group"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "Group": {
            "type": "object",
            "properties": {
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Match"
                    },
                    "uniqueItems": true,
                    "minItems": 1
                },
                "teams": {
                    "$ref": "#/definitions/Teams"
                },
                "tops": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 1
                    },
                    "uniqueItems": true,
                    "minItems": 1
                }
            },
            "required": [
                "matches",
                "teams",
                "tops"
            ],
            "additionalProperties": false
        },
        "Match": {
            "type": "object",
            "properties": {
                "a": {
                    "type": "string"
                },
                "b": {
                    "type": "string"
                },
                "possibilities": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "a": {
                                "type": "integer"
                            },
                            "b": {
                                "type": "integer"
                            }
                        },
                        "required": [
                            "a",
                            "b"
                        ],
                        "additionalProperties": false
                    },
                    "uniqueItems": true,
                    "minItems": 1
                }
            },
            "required": [
                "a",
                "b",
                "possibilities"
            ],
            "additionalProperties": false
        },
        "Teams": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        }
    }
};
// @ts-ignore
export function indexTemplateHtml(this: Main) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{staticClass:"main"},[_c('div',{ref:"mainEditor",staticClass:"editor"}),(_vm.errorMessage)?_c('div',{staticClass:"error-message"},[_vm._v(_vm._s(_vm.errorMessage))]):_vm._e(),_c('button',{on:{"click":function($event){_vm.calculate()}}},[_vm._v(_vm._s(_vm.progressText || "Calculate"))]),_c('div',{staticClass:"result"},_vm._l((_vm.result),function(group,i){return _c('table',{key:i},[_c('thead',[_c('tr',[_c('th',[_vm._v("group "+_vm._s(i + 1))]),_vm._l((group.tops),function(top,j){return _c('th',{key:j},[_vm._v("top "+_vm._s(top)+" chance(%)")])}),_c('th',[_vm._v("score")]),_c('th',[_vm._v("match count left")])],2)]),_c('tbody',_vm._l((group.chances),function(team,j){return _c('tr',{key:j},[_c('td',[_vm._v(_vm._s(team.name))]),_vm._l((team.chances),function(chance,k){return _c('td',{key:k},[_vm._v(_vm._s(chance))])}),_c('td',[_vm._v(_vm._s(team.score))]),_c('td',[_vm._v(_vm._s(team.matchCountLeft))])],2)}))])}))])}
export const teamsSchemaJson = {
    "$ref": "#/definitions/Teams",
    "definitions": {
        "Teams": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        }
    }
};
// tslint:enable
